// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AnalyzeSubtitlesByContent(arg1:Array<main.SubtitleItem>,arg2:string,arg3:string):Promise<main.IntelligentPPTResult>;

export function BuildWhisperImage():Promise<Record<string, any>>;

export function CheckQwenAPIKey():Promise<main.APIKeyResult>;

export function CheckTranslateStatus():Promise<Record<string, any>>;

export function CheckWhisperStatus():Promise<Record<string, any>>;

export function ExportIntelligentPPTResult(arg1:main.IntelligentPPTResult):Promise<string>;

export function ExportPPTResult(arg1:main.PPTResult):Promise<string>;

export function ExportSubtitlesToJSON(arg1:Array<main.SubtitleItem>,arg2:string):Promise<main.ExportSubtitleResult>;

export function ExtractPPTFrames(arg1:string,arg2:number):Promise<main.PPTResult>;

export function FormatTime(arg1:number):Promise<string>;

export function GenerateSubtitle(arg1:string,arg2:string,arg3:string):Promise<main.SubtitleResult>;

export function GetCurrentSubtitle(arg1:Array<main.SubtitleItem>,arg2:number):Promise<main.SubtitleItem>;

export function Greet(arg1:string):Promise<string>;

export function ImportSubtitleFromJSON(arg1:string):Promise<main.ImportSubtitleResult>;

export function InstallWhisper():Promise<Record<string, any>>;

export function ParseTime(arg1:string):Promise<number>;

export function SaveQwenAPIKey(arg1:string):Promise<main.SaveAPIKeyResult>;

export function SelectSubtitleFile():Promise<string>;

export function SelectVideoFile():Promise<string>;

export function SummarizeSubtitles(arg1:Array<main.SubtitleItem>,arg2:string,arg3:string,arg4:string):Promise<main.SummarizeResult>;

export function TranslateSubtitles(arg1:Array<main.SubtitleItem>):Promise<main.TranslateResult>;

export function TranslateSubtitlesWithQwen(arg1:Array<main.SubtitleItem>):Promise<main.CloudTranslateResult>;

export function TranslateText(arg1:string):Promise<Record<string, any>>;
