// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnalyzeSubtitlesByContent(arg1, arg2) {
  return window['go']['main']['App']['AnalyzeSubtitlesByContent'](arg1, arg2);
}

export function BuildWhisperImage() {
  return window['go']['main']['App']['BuildWhisperImage']();
}

export function CheckQwenAPIKey() {
  return window['go']['main']['App']['CheckQwenAPIKey']();
}

export function CheckTranslateStatus() {
  return window['go']['main']['App']['CheckTranslateStatus']();
}

export function CheckWhisperStatus() {
  return window['go']['main']['App']['CheckWhisperStatus']();
}

export function ExportIntelligentPPTResult(arg1) {
  return window['go']['main']['App']['ExportIntelligentPPTResult'](arg1);
}

export function ExportPPTResult(arg1) {
  return window['go']['main']['App']['ExportPPTResult'](arg1);
}

export function ExportSubtitlesToJSON(arg1, arg2) {
  return window['go']['main']['App']['ExportSubtitlesToJSON'](arg1, arg2);
}

export function ExtractPPTFrames(arg1, arg2) {
  return window['go']['main']['App']['ExtractPPTFrames'](arg1, arg2);
}

export function FormatTime(arg1) {
  return window['go']['main']['App']['FormatTime'](arg1);
}

export function GenerateSubtitle(arg1, arg2, arg3) {
  return window['go']['main']['App']['GenerateSubtitle'](arg1, arg2, arg3);
}

export function GetCurrentSubtitle(arg1, arg2) {
  return window['go']['main']['App']['GetCurrentSubtitle'](arg1, arg2);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ImportSubtitleFromJSON(arg1) {
  return window['go']['main']['App']['ImportSubtitleFromJSON'](arg1);
}

export function InstallWhisper() {
  return window['go']['main']['App']['InstallWhisper']();
}

export function ParseTime(arg1) {
  return window['go']['main']['App']['ParseTime'](arg1);
}

export function SaveQwenAPIKey(arg1) {
  return window['go']['main']['App']['SaveQwenAPIKey'](arg1);
}

export function SelectSubtitleFile() {
  return window['go']['main']['App']['SelectSubtitleFile']();
}

export function SelectVideoFile() {
  return window['go']['main']['App']['SelectVideoFile']();
}

export function SummarizeSubtitles(arg1, arg2) {
  return window['go']['main']['App']['SummarizeSubtitles'](arg1, arg2);
}

export function TranslateSubtitles(arg1) {
  return window['go']['main']['App']['TranslateSubtitles'](arg1);
}

export function TranslateSubtitlesWithQwen(arg1) {
  return window['go']['main']['App']['TranslateSubtitlesWithQwen'](arg1);
}

export function TranslateText(arg1) {
  return window['go']['main']['App']['TranslateText'](arg1);
}
