// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function BuildWhisperImage():Promise<Record<string, any>>;

export function CheckTranslateStatus():Promise<Record<string, any>>;

export function CheckWhisperStatus():Promise<Record<string, any>>;

export function FormatTime(arg1:number):Promise<string>;

export function GenerateSubtitle(arg1:string,arg2:string,arg3:string):Promise<main.SubtitleResult>;

export function GetCurrentSubtitle(arg1:Array<main.SubtitleItem>,arg2:number):Promise<main.SubtitleItem>;

export function Greet(arg1:string):Promise<string>;

export function InstallWhisper():Promise<Record<string, any>>;

export function ParseTime(arg1:string):Promise<number>;

export function SelectVideoFile():Promise<string>;

export function TranslateSubtitles(arg1:Array<main.SubtitleItem>):Promise<main.TranslateResult>;

export function TranslateText(arg1:string):Promise<Record<string, any>>;
